### ISSUE TITLE
Run Code error

### ISSUE THREAD

**Issue by Rzx520** [orrzohar/PROB#29] opened 2023-07-17 07:57 UTC
'AuntimeError: Timed out initializn process group in store based barrier on rank: 2,for key: store based barier key:l. (world size-3. worker counte,timeot=0:30:00)'
I would like to ask why it only occurs in rank2?I can run one epoch normally, but every time I run the second epoch, an error occurs and one GPU stops running. Why is that?@orrzohar
When running the code, give a warning as follows. Will this have an impact？
UserWarning:The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
UserWarning: Arguments other than a weight enum or 'None" for 'weights' are deprecated since 0.13 and wili be removed in 0.15. The current behavior is equivalent to passing 'weights = None'

**Comment by orrzohar** [comment] 2023-07-17 22:59
Hi @Rzx520,

Could you give me some more details about your system? 
Which GPUs/CUDA are you using?
Are you using this codebases distributed process code?

Best,
Orr

**Comment by Rzx520** [comment] 2023-07-18 04:36
Hello, I already know that it is a GPU issue. Setting the batch size to 1 can solve it. I am using 4 12G 1080. I see a problem where someone has suggested using 4 12G GPUs for training (batch size=2), but I am not good at it. I am very confused about this.@orrzohar

**Comment by orrzohar** [comment] 2023-07-18 23:42
Hi @Rzx520,

Hmm, I see.

Could you run on your system with a single GPU (Not using distributed process, just directly triggering the main script) and see if the error changes? You may be running out of memory in epoch 2, and the distributed data-parallel may be masking the error handling. 

If the issue is indeed running out of memory (as your results suggest, as reducing the batch size seems to remove this issue), then that is the only available solution (I have no other way of reducing the GPU consumption).

Luckily I use exponential smoothing in calculating the prob. objectness distribution parameters, so objectness estimation should be only marginally affected. As to the known objects performance, we will find out...


Best,
Orr

**Comment by Rzx520** [comment] 2023-07-19 01:28
I am currently training with batch size=1 and I would like to see how much impact the final result will have.@orrzohar

**Comment by Rzx520** [comment] 2023-07-19 01:43
![image](https://github.com/orrzohar/PROB/assets/74809549/c7e47f03-7262-45cb-8d61-bfb619402991)
![image](https://github.com/orrzohar/PROB/assets/74809549/ffb08d7f-3f24-4e8f-8525-7f59fc0d3fe7)
This is the result of training t1 with batch size=1, is this very abnormal?@orrzohar

**Comment by orrzohar** [comment] 2023-07-21 18:12
Hi @Rzx520 ,

Yes, I would say so,

This looks like what the error plots look like during the first few iterations in epoch 1. but it seems like you have already trained well beyond that.

Did you perhaps reduce your lr significantly? have you tried using the lr reported in OW-DETR?

Best,
Orr

**Comment by Rzx520** [comment] 2023-07-22 02:57
Yes, I used the parameter settings for OW-DETR, but set the batch size to 1. @orrzohar

**Comment by orrzohar** [comment] 2023-07-22 18:33
Hi @Rzx520, 
Try increasing and decreasing the lr by a factor of 2.

Usually, when decreasing the batch size you want to decrease the lr, but from looking at these plots it does look like you have the learning rate too low... so I am not sure which is the correct way to go. 

If neither options work, I am worried that you may need at least a batch size of 2 to train the model. An option is to decrease the image size, but then the numbers won't be the same..

Best,
Orr

**Comment by Rzx520** [comment] 2023-07-23 05:05
Can we use two 3090 (24G) instead of four 1080 (12G) and set the batch size to 4?

**Comment by orrzohar** [comment] 2023-07-23 17:54
Yes, that would be better than 4 1080s

**Comment by Rzx520** [comment] 2023-07-24 09:18
Can you provide a visual code for the detection results?@orrzohar thanks

**Comment by orrzohar** [comment] 2023-07-25 16:05
Hi @Rzx520,

Unfortunately, I used GCP for the project & did not keep the visualization code. Please see https://github.com/orrzohar/PROB/issues/11 https://github.com/orrzohar/PROB/issues/21 for discussions on how to re-create the visualizations.

It is relatively straightforward. If you do get it working, you could even put a PR in, and I will add it to the codebase,

Best,
Orr

**Comment by Rzx520** [comment] 2023-07-26 06:19
Regarding the sentence you said 'cycled through the GT (both known and unknown) objects, and if a model had a prediction of the same class/IoU>0.5, I added that bbox on the image',
I would like to know if there are many predicted bbox matches(IoU>0.5 for the same GT) when you cycled through GT. Have you added them all or did you do anything about it?@orrzohar

**Comment by orrzohar** [comment] 2023-07-27 16:42
Hi @Rzx520,
Once I had one detection for a GT, I effectively "removed" that labeled instance. 

In plotting, I followed the protocol for calculating mAP and plotted all the TPs. I opted to do this as this would best reflect the numerical results.

If you were to draw on also the FPs, you would be plotting 100 bbox per image unless you applied some additional filtering of the boxes (e.g., confidence threshold, NMS, as discussed in a previous issue). This would be more realistic in a real inference scenario.

Regarding whether the model made multiple TP object predictions on the same object - I seem to remember that it did, but to be sure, you could take the released weights and plot the predictions -- that should be 100% reproducible.

Best,
Orr

**Comment by orrzohar** [comment] 2023-07-27 16:43
Also, as it seems like the "code run error" has been resolved, I am closing this issue -- if you have a new issue feel free to open one or re-open this issue if the GPU timeout is not resolved.

Best,
Orr

**Closed as completed by orrzohar** 2023-07-27 16:43 UTC

**Comment by Rzx520** [comment] 2023-07-28 00:35
> Also, as it seems like the "code run error" has been resolved, I am closing this issue -- if you have a new issue feel free to open one or re-open this issue if the GPU timeout is not resolved.

So when visualizing, every time you detect a prediction corresponding to a GT, you add the bbox corresponding to the prediction for that GT, and then ignore (equivalent to deleting the GT) any predictions about the same GT. Is this understanding correct? You should have made a ranking, right? Although there are many predictions for the same GT in the future, the ones with higher scores are drawn first?@orrzohar

**Comment by Rzx520** [comment] 2023-07-28 00:35
> Hi @Rzx520, Once I had one detection for a GT, I effectively "removed" that labeled instance.
> 
> In plotting, I followed the protocol for calculating mAP and plotted all the TPs. I opted to do this as this would best reflect the numerical results.
> 
> If you were to draw on also the FPs, you would be plotting 100 bbox per image unless you applied some additional filtering of the boxes (e.g., confidence threshold, NMS, as discussed in a previous issue). This would be more realistic in a real inference scenario.
> 
> Regarding whether the model made multiple TP object predictions on the same object - I seem to remember that it did, but to be sure, you could take the released weights and plot the predictions -- that should be 100% reproducible.
> 
> Best, Orr

So when visualizing, every time you detect a prediction corresponding to a GT, you add the bbox corresponding to the prediction for that GT, and then ignore (equivalent to deleting the GT) any predictions about the same GT. Is this understanding correct? You should have made a ranking, right? Although there are many predictions for the same GT in the future, the ones with higher scores are drawn first?@orrzohar
